version: "3.3"
services:
    # notebook
    notebook:
        build:
            context: ./jupyter-notebook-docker 
        ports: 
            - ${JUPYTER_NOTEBOOKS_PORT}:${JUPYTER_NOTEBOOKS_PORT} 
        depends_on: 
            - mlflow 
        environment: 
            MLFLOW_TRACKING_URI: "http://mlflow:5000" 
        volumes: 
            - ./notebooks:/notebooks
    mlflow:
        build:
            context: ./ml-flow-docker
        expose: 
            - "5000"
        ports:
            - "5000:5000"
        depends_on: 
            - postgres
    postgres:
        build:
            context: ./postgres-docker
        restart: always
        environment:
            POSTGRES_USER: 'admin'
            POSTGRES_PASSWORD: 'secret'
        ports: 
            - "5432:5432"
        volumes:
            - "./postgres-store:/var/lib/postgresql/data"
    
volumes:
    postgres-store:
    notebooks: